CREATE DATABASE IF NOT EXISTS mujeres,
USE mujeres
CREATE TABLE IF NOT EXISTS mujeres(
    nombre VARCHAR(100) NOT NULL PRIMARY KEY,
    email VARCHAR(50) NOT NULL,
    password VARCHAR(255) NOT NULL
)