CREATE DATABASE IF NOT EXISTS mujeres,
USE mujeres
CREATE TABLE IF NOT EXISTS digitales(
    id int(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    email VARCHAR(50) NOT NULL,
    password VARCHAR(255) NOT NULL
)